MVCAutentimisegaEsimene/MVCAutentimisegaEsimene/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCAutentimisegaEsimene.Models;

namespace MVCAutentimisegaEsimene.Controllers
{
    public class RolesController : Controller
    {
        private Entities db = new Entities();

        // GET: Roles
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
                return View(db.AspNetRoles.ToList());
            else
                return RedirectToAction("Index", "Home");
        }

        // GET: Roles/Details/5
        [Authorize(Roles ="Administrator")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.AspNetRoles.Add(aspNetRole);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetRole);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetRole).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetRole);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRole);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCAutentimisegaEsimene/MVCAutentimisegaEsimene/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCAutentimisegaEsimene.Models;

namespace MVCAutentimisegaEsimene.Models
{
    partial class AspNetUser
    {
        public string RoleId { get; set; }
        public string RoleName => AspNetRoles.FirstOrDefault()?.Name;
    }

}

namespace MVCAutentimisegaEsimene.Controllers
{
    public class UsersController : Controller
    {
        public List<string> GetAllCountries()
        {
            return CultureInfo.GetCultures(CultureTypes.AllCultures)
                .Select(x => x.EnglishName)
                .ToList();
        }


        private Entities db = new Entities();

        // GET: Users
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
                return View(db.AspNetUsers.ToList());
            else
                return RedirectToAction("Index", "Home");
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }

            
            // võtame rollide hulgast ainult need, mille kasutajate hulgas ei ole
            // konkreetset kasutajat (aspNetUser)
            ViewBag.Roles = db.AspNetRoles
              .Where(r => ! r.AspNetUsers.Select(x => x.Email).Contains(aspNetUser.Email))
              .ToList();

            return View(aspNetUser);
        }

        public ActionResult AddRole(string id, string role)
        {
            AspNetUser u = db.AspNetUsers.Find(id);
            if (u != null) db.RemoveRoles(u.Id);
            db.SaveChanges();
            AspNetRole r = db.AspNetRoles.Find(role);
            if (u != null && r != null)
            {
                try
                {
                    u.AspNetRoles.Add(r);
                    db.SaveChanges();
                }
                catch { }
            }

            return RedirectToAction("Details", new { id });
        }

        public ActionResult RemoveRole(string id, string role)
        {
            AspNetUser u = db.AspNetUsers.Find(id);
            AspNetRole r = db.AspNetRoles.Find(role);
            if (u != null && r != null)
            {
                try
                {
                    u.AspNetRoles.Remove(r);
                    db.SaveChanges();
                }
                catch { }
            }

            return RedirectToAction("Details", new { id });
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.RoleId = new SelectList(db.AspNetRoles, "Id", "Name");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DisplayName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,RoleId")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                AspNetRole role = db.AspNetRoles.Find(aspNetUser.RoleId);
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                if(role != null)
                {
                    aspNetUser.AspNetRoles.Add(role);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(db.AspNetRoles, "Id", "Name");
            return View(aspNetUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Countries = GetAllCountries();
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            aspNetUser.RoleId = aspNetUser.AspNetRoles.FirstOrDefault()?.Id;
            ViewBag.RoleId = new SelectList(db.AspNetRoles, "Id", "Name", aspNetUser.RoleId);
            return View(aspNetUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DisplayName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,RoleId")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                db.RemoveRoles(aspNetUser.Id);
                db.SaveChanges();
                AspNetRole role = db.AspNetRoles.Find(aspNetUser.RoleId);
                if(role != null)
                {
                    aspNetUser.AspNetRoles.Add(role);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            aspNetUser.RoleId = aspNetUser.AspNetRoles.FirstOrDefault()?.Id;
            ViewBag.RoleId = new SelectList(db.AspNetRoles, "Id", "Name", aspNetUser.RoleId);

            return View(aspNetUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCAutentimisegaEsimene/MVCAutentimisegaEsimene/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Style the header */
        header {
            background-color: #666;
            padding: 30px;
            text-align: center;
            font-size: 35px;
            color: white;
        }

        /* Container for flexboxes */
        section {
            display: -webkit-flex;
            display: flex;
        }

        /* Style the navigation menu */
        nav {
            -webkit-flex: 1;
            -ms-flex: 1;
            flex: 1;
            background: #ccc;
            padding: 20px;
        }

            /* Style the list inside the menu */
            nav ul {
                list-style-type: none;
                padding: 0;
            }

        /* Style the content */
        article {
            -webkit-flex: 3;
            -ms-flex: 3;
            flex: 3;
            background-color: #f1f1f1;
            padding: 10px;
        }

        /* Style the footer */
        footer {
            background-color: #777;
            padding: 10px;
            text-align: center;
            color: white;
        }

        /* Responsive layout - makes the menu and the content (inside the section) sit on top of each other instead of next to each other */
        @@media (max-width: 600px) {
            section {
                -webkit-flex-direction: column;
                flex-direction: column;
            }
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">

                    <li class="bar-home">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="bar-about">@Html.ActionLink("About", "About", "Home")</li>
                    <li class="bar-contact">@Html.ActionLink("Contact", "Contact", "Home")</li>


                </ul>


                @Html.Partial("_LoginPartial")

                @if (Request.IsAuthenticated)
                {
                    if (User.IsInRole("Administrator"))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active">@Html.ActionLink("Kasutajad", "Index", "Users")</li>
                            <li>@Html.ActionLink("Rollid", "Index", "Roles")</li>

                        </ul>
                    }
                }

            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@
    <script src="~/Content/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
    <link href="~/Content/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
    <script src="~/Content/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.datepicker').datepicker({
                dateFormat: 'dd.mm.yy',
                changeMonth: true,
                changeYear: true
            });
            $('.a-submit').click(
                function () {
                    //$(this).closest('form').submitForm();
                    $(this).parents('form').submit();
                }
            );
        });
    </script>
    <style>

           .@ViewBag.Bar
        {
           background-color : blue;
        }
    </style>


    @*Kui tahad oma datepickeri eestikeelseks teha,
        lisad eelneva scripti JÄRELE veel mõned read*@

    <script>
        /* Estonian initialisation for the jQuery UI date picker plugin. */
        /* Written by Mart Sõmermaa (mrts.pydev at gmail com). */
        (function (factory) {
            if (typeof define === "function" && define.amd) {
                // AMD. Register as an anonymous module.
                define(["../widgets/datepicker"], factory);
            } else {
                // Browser globals
                factory(jQuery.datepicker);
            }
        }(function (datepicker) {
            datepicker.regional.et = {
                closeText: "Sulge",
                prevText: "Eelnev",
                nextText: "Järgnev",
                currentText: "Täna",
                monthNames: ["Jaanuar", "Veebruar", "Märts", "Aprill", "Mai", "Juuni",
                    "Juuli", "August", "September", "Oktoober", "November", "Detsember"],
                monthNamesShort: ["Jaan", "Veebr", "Märts", "Apr", "Mai", "Juuni",
                    "Juuli", "Aug", "Sept", "Okt", "Nov", "Dets"],
                dayNames: [
                    "Pühapäev",
                    "Esmaspäev",
                    "Teisipäev",
                    "Kolmapäev",
                    "Neljapäev",
                    "Reede",
                    "Laupäev"
                ],
                dayNamesShort: ["Pühap", "Esmasp", "Teisip", "Kolmap", "Neljap", "Reede", "Laup"],
                dayNamesMin: ["P", "E", "T", "K", "N", "R", "L"],
                weekHeader: "näd",
                dateFormat: "dd.mm.yy",
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ""
            };
            datepicker.setDefaults(datepicker.regional.et);
            return datepicker.regional.et;
        }));
    </script>

</body>

</html>